= {% autotitle %}{% endautotitle %}
:icons: font

This book is an introductory course of *Visual Basic.NET*.
Before we dive into the VB.NET, a few basic ideas of programming are introduced here.


== What is programming?

*Programming* is the process of designing, writing, testing and debugging (remove mistakes from) a program.
To write a program, you need to know and solve the problem first.
After solving the problem, you tell the computer how to solve the problem using a *programming language*.

For example, if you need to write a program that calculates percentage changes, you should first solve the problem by obtaining the formula of percentage change.
After that, you will write a program to do the task.

To get the idea of how to create a computer program, you may refer to the diagram below.
(Note: after having a finished program, you can do an evaluation to look for possible improvements.)

[.text-center]
+++{% include "../diagrams/programming.svg" %}+++

<<<
== What is a programming language

In computers, instructions are stored in *machine code*, that each instruction (e.g. ADD, SUBTRACT, MULTIPLY, etc.) is given a unique number.
Computers can understand machine code only.

However, machine codes are very difficult to be understood by human.
Therefore, *programming languages*, that are understandable by human, are created to bridge the gap.

A programming language consists of a *specification* and an *implementation*.
The specification provides a definition of the programming language, and programmers write programs according to the specification.
And the implementation is a translator: something that converts the program from the programming language into machine code.


== Compilers and interpreters

*Compilers* are a type of translator that converts source code into an object program.
The object program is stored in an executable file (.exe in Windows), which can be executed directly in a computer.
The usage of a compiler can be summarized in the diagram below:

[.text-center]
+++{% include "../diagrams/compilation.svg" %}+++

On the contrary, an *interpreter* reads the instructions one by one, and execute each instruction immediately after reading it.
No object program is made by the interpreter.
This approach may sound simpler, but its efficiency is generally much lower than compilers because the same program statement needs to be translated every time it is run.


<<<
== Bytecode and virtual machines

In some programming languages, including Java and Visual Basic.NET, programs are not directly compiled to machine code.
Instead, they are compiled to some intermediate representation called *bytecode*.

The generated bytecode is opened and executed by a *virtual machine (VM)*.
A virtual machine is actually a translator of the bytecode, which consists of an interpreter or a just-in-time (JIT) compiler, or both.


== Just-in-time compilation

*Just-in-time (JIT) compilation* means doing the compilation at run-time, instead of prior to execution.
This is generally more efficient than interpreters because compilation is only done once.
However, there is a small delay at the start of execution because of the compilation.

Java, JavaScript and .NET framework are a few popular systems that utilise JIT compilation.


// Uncomment the following lines if fonts are missing.
[.phantom]
icon:tags[] a _a_ `a` $$\left( \frac{a}{1^2} \right)$$

[.phantom.sans]
123
