= {% autotitle %}{% endautotitle %}
:icons: font

Professional programmers work with projects with hundreds of source files.
It is very important to keep programs maintainable, in particular easy to read.


== Indentation

One of the standard practice is to indent the code inside each statement block, i.e. shift the code to the right.
Fortunately, you do not need to know the details now, because Visual Studio indents your code automatically.


== Comments

Comments are messages in the source code that are intended to be read by humans.
They are ignored by compilers.
In Visual Basic, comments start with a single quote (`'`), which is followed by any text you want.
Here is an example:

[source, vb]
....
Module Module1
    Sub Main()
        ' This is a comment that occupy for a whole line.
        Console.WriteLine("Hello world!")  ' Another comment
        Console.ReadLine()
    End Sub
End Module
....


== Appendix: Option Strict On

To produce good code in Visual Basic, it is advised to write `Option Strict On` on the first line of every `.vb` file.
This forbids a few types of implicit conversions, including the implicit conversion from string to numbers.
Once you can handle the conversion properly (using `Val` is not handling properly), you should use that options in your Visual Basic code.
