= {% autotitle %}{% endautotitle %}
:icons: font

In the last section, the word `And` is a logical operator in Visual Basic.
Here three logical operators are studied: `Not`, `And`, `Or`.
Here are their meanings:

[options="header", cols="^1l, 3, 3a"]
|===
|Operator |Meaning |Syntax
|Not |Negation. True/False are inverted. |[source, vb]
Not condition1
|And |See if all conditions are true. |[source, vb]
condition1 And condition2
|Or |See if one or more conditions are true. |[source, vb]
condition1 Or condition2
|===


== Truth tables

To understand a logical operator, we construct a table to list its possible inputs and outputs.
This table is known as truth table.
Now complete the following truth tables by writing down the results (`True` or `False`).

[options="header", cols="^1l, ^1l, ^1l"]
.`And` operator
|===
|_a_ |_b_ |_a_ `And` _b_
|True |True |
|True |False |
|False |True |
|False |False |
|===

[options="header", cols="^1l, ^1l, ^1l"]
.`Or` operator
|===
|_a_ |_b_ |_a_ `Or` _b_
|True |True |
|True |False |
|False |True |
|False |False |
|===

[options="header", cols="^1l, ^1l"]
.`Not` operator
|===
|_a_ |`Not` _a_
|True |
|False |
|===


== Order of operations

The evaluation of expressions in Visual Basic is ordered by its operator precedence below.

[cols="^1, 3, ^2l"]
|===
|11 (Highest) |Exponentiation |^
|10 |Unary identity and negation |(unary)+ (unary)–
|9 |Multiplication and floating-point division |* /
|8 |Integer division |\
|7 |Modulus arithmetic |Mod
|6 |Addition and subtraction |+ –
|5 |String concatenation |&
|4 |Relational/comparison operators |= <> < \<= > >=
|3 |Negation |Not
|2 |Conjunction |And
|1 (Lowest) |Inclusive disjunction |Or
|===

[TIP]
====
`Not` is evaluated before `And`, and `And` is evaluated before `Or`.
Add a pair of parenthesis if this is not what you want.
====

[NOTE]
====
Operators introduced in later chapters are also listed here. +
An unary operator has only one expression next to it, e.g. the minus in $$ (-3)^2 $$.
====


== Class work

Convert the following to Visual Basic conditions.
The names of the variables are underlined.

[options="header" cols="1,l"]
|===
|Comparisons |Visual Basic condition
|If the [underlined]_mark_ is outside the range $$ 0 \le y \le 100 $$. |
|If the [underlined]_guess_ is between 5 and 9 (both inclusive). |
|If the [underlined]_day_ is “Mon” or “Tue” |
|If the [underlined]_sex_ is “M” and the [underlined]_weight_ is greater than 80 (kg). |
|If the [underlined]_age_ is not less than 65, and [underlined]_today_ is “Sat”. |
|===

[TIP]
====
Inclusive means include the end values (5 and 9 in the question).
The opposite of inclusive is exclusive.
====


Evaluate the following Visual Basic Expressions. +
_Hint: The result is either `True` or `False`._

[options="header" cols="4l,3"]
|===
|VB expression |Result
|4 > 2 And 1 = 3 |
|20 < -5 Or 3 >= 3 |
|-5 \<= -7 Or 3 / 2 > 2 |
|1 > -2 And 5 / 7 >= 3 / 5 |
|Not (5 ^ 2 >= 2 ^ 5) |
|Not (6 \<= -2 And 7 > 12) |
|1 > 2 And 3 = 4 Or 5 \<= 6 |
|Not True And Not False |
|===


Convert the following mathematical expressions to Visual Basic conditions:
[options="header" cols="^1,1"]
|===
|Mathematical expression |Visual Basic condition
| $$0 < a < 18$$ |
| $$x \le y \le z$$ |
| $$a > 0 > b$$ |
|===


== Example
[source, vb]
....
Console.Write("Enter your age: ")
Dim age As Integer = Console.ReadLine()

Console.Write("Enter your sex (M/F): ")
Dim sex As String = Console.ReadLine()

If age > 0 And age < 18 And sex = "F" Then
    Console.WriteLine("Welcome to the dreamland!")
Else
    Console.WriteLine("No entry.")
End If

Console.ReadLine()
....

Here is the output:

[role="sample-output", subs="normal"]
....
Enter your age: [userinput]#17#
Enter your sex (M/F): [userinput]#F#
Welcome to the dreamland!
....
